apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: auth-db
  template:
    metadata:
      labels:
        svc: auth-db
    spec:
      containers:
        - name: postgres
          image: postgres@sha256:04a3d3d1475ad37f07d8219d0e5eb46f64ac132bf6e110c772dab45e12e4a919    # CK-03 remediated: digest-pinned (postgres:14 as of Day 7)
          env:
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_USER
              value: authuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: AUTH_DB_PASSWORD
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: secureflow
spec:
  selector:
    svc: auth-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-db
  namespace: secureflow
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: transaction-db
  template:
    metadata:
      labels:
        svc: transaction-db
    spec:
      containers:
        - name: postgres
          image: postgres@sha256:04a3d3d1475ad37f07d8219d0e5eb46f64ac132bf6e110c772dab45e12e4a919    # CK-03 remediated: digest-pinned (postgres:14 as of Day 7)
          env:
            - name: POSTGRES_DB
              value: transactiondb
            - name: POSTGRES_USER
              value: txuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: TX_DB_PASSWORD
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-db
  namespace: secureflow
spec:
  selector:
    svc: transaction-db
  ports:
    - port: 5432
      targetPort: 5432
