apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: secureflow
  labels:
    app: frontend
    team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: frontend
  template:
    metadata:
      labels:
        svc: frontend
        app: frontend
        team: platform
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "frontend"
        vault.hashicorp.com/agent-inject-secret-config: "secureflow/data/frontend"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secureflow/data/frontend" -}}
          export SESSION_SECRET="{{ .Data.data.SESSION_SECRET }}"
          export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
          {{- end -}}
    spec:
      serviceAccountName: frontend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: ghcr.io/ade820/secureflow-frontend@sha256:dc04e1be01f33e4d1a7e905bcaef78e8043d4d7baf7e09333f3fdc7046101c2b
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - ". /vault/secrets/config && exec python app.py"
          ports:
            - containerPort: 5000
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: secureflow
spec:
  type: NodePort
  selector:
    svc: frontend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
