{
 "title": "SecureFlow Security Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Falco Security Alerts (live)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"falco\"} |= \"secureflow\" != \"schema validation\""
    }
   ]
  },
  {
   "title": "OPA Gatekeeper (Active pods)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"gatekeeper-system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secureflow Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"secureflow\",phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers with Memory Limits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_resource_limits{namespace=\"secureflow\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"secureflow\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secureflow Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"secureflow\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secureflow CPU Usage by Pod panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"secureflow\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Falco Alerts (1h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=\"falco\"} |= \"Warning\" [1h]))"
    }
   ]
  }
 ]
}